In [2]:
import pandas as pd

## **Questions based on Titanic Dataset:**

To read the dataset as csv, use the below code:

```python
import pandas as pd

url = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQjh5HzZ1N0SU7ME9ZQRzeVTaXaGsV97rU8R7eAcg53k27GTstJp9cRUOfr55go1GRRvTz1NwvyOnuh/pub?gid=1562145139&single=true&output=csv"
titanic_df = pd.read_csv(url)
```

In [76]:
titanic_df = pd.read_csv('dataset/train - train.csv')

### `Q-1:` Using `groupby` make groups using the `"Pclass"` column and find out the average age and total number of missing values in the `"Age"` column for every group.

In [5]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [22]:
# 1.  find out the average age 
titanic_df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [26]:
# 2. total number of missing values in the "Age"
titanic_df.groupby('Pclass')['Age'].apply(lambda x: x.isna().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

In [28]:
# 2. total number of missing values in the "Age"
titanic_df.groupby('Pclass')['Age'].agg(lambda x: x.isna().sum())

Pclass
1     30
2     11
3    136
Name: Age, dtype: int64

In [32]:
titanic_df.groupby('Pclass')['Age'].agg(
    avg_mean = 'mean',
    missing_values = lambda x: x.isna().sum()
)

         avg_mean  missing_values
Pclass
1       38.233441              30
2       29.877630              11
3       25.140620             136

### `Q-2:` Using `groupby` make groups using the `"Pclass"` column and fill every group's `"Embarked"` column's missing values with the mode value of that group. After that, print every group's `"Embarked"` column's value counts in ascending order.

In [36]:
titanic_df.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [79]:
# 1. fill every group's "Embarked" column's missing values with the mode value of that group
titanic_df['Embarked'].isna().sum()

np.int64(2)

In [80]:
titanic_df['Embarked'] = titanic_df.groupby('Pclass')['Embarked'].transform(lambda x: x.fillna(x.mode()[0]))

titanic_df['Embarked'].isna().sum()

np.int64(0)

In [89]:
# 2. print every group's "Embarked" column's value counts in ascending order
titanic_df.groupby('Pclass').groups

{1: [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 2: [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 3: [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [111]:
for name, group in titanic_df.groupby('Pclass'):
    print(name)
    print(group["Embarked"].value_counts())
    print()

1
Embarked
S    129
C     85
Q      2
Name: count, dtype: int64

2
Embarked
S    164
C     17
Q      3
Name: count, dtype: int64

3
Embarked
S    353
Q     72
C     66
Name: count, dtype: int64

In [112]:
titanic_df.groupby('Pclass')['Embarked'].value_counts()

Pclass  Embarked
1       S           129
        C            85
        Q             2
2       S           164
        C            17
        Q             3
3       S           353
        Q            72
        C            66
Name: count, dtype: int64

In [118]:
titanic_df.groupby('Pclass')['Embarked'].value_counts().reset_index(name='count')

   Pclass Embarked  count
0       1        S    129
1       1        C     85
2       1        Q      2
3       2        S    164
4       2        C     17
5       2        Q      3
6       3        S    353
7       3        Q     72
8       3        C     66

In [120]:
result = titanic_df.groupby('Pclass')['Embarked'].value_counts().unstack()
result

Embarked   C   Q    S
Pclass
1         85   2  129
2         17   3  164
3         66  72  353

In [114]:
pd.crosstab(titanic_df['Pclass'], titanic_df['Embarked'])

Embarked   C   Q    S
Pclass
1         85   2  129
2         17   3  164
3         66  72  353

### `Q-3:` Make groups based on `"Embarked"` column. And for each of this embarked group, make another group based on `"Pclass"` and find out the average fare (round off up to 2 decimal places) for each "Pclass" for each group of "Embarked".

**Sample Output:**

```bash
{'C': {1: 105, 2: 25, 3: 11},
 'Q': {1: 90, 2: 12, 3: 11},
 'S': {1: 70, 2: 20, 3: 15}}
```

In [146]:
titanic_df.groupby(['Embarked', 'Pclass'])['Fare'].mean()

Embarked  Pclass
C         1         104.718529
          2          25.358335
          3          11.214083
Q         1          90.000000
          2          12.350000
          3          11.183393
S         1          70.514244
          2          20.327439
          3          14.644083
Name: Fare, dtype: float64

In [143]:
titanic_df.groupby(['Embarked', 'Pclass'])['Fare'].mean().round(2).unstack()

Pclass         1      2      3
Embarked
C         104.72  25.36  11.21
Q          90.00  12.35  11.18
S          70.51  20.33  14.64

## **Questions Based on Fifa Worldcup - 2022 Dataset:**

You can read the dataset by using the below sample code

```python
import pandas as pd

fifa_df = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT3D_x_4DS6d51LKJ7ze1sxT5WpV5uiSVOFYHLwBiGru6vFyVv5h5-83AwFjxWYiWfCDjDAaarHAV-k/pub?gid=0&single=true&output=csv")
```

### `Q-4:` Perform `groupby` based on the `"Team"` column and then perform Z Normalization on top of the below columns of each group:
1. Passes
2. Passes Completed
3. Attempted Line Breaks
4. Completed Line Breaks

You have to make a python function named `z_normalization` which takes two arguments:

1. *group:* Every group that you have created
2. *cols_to_perform:* This parameter takes a list of columns on which you have to perform the Z-Normalization.

For this problem, you have to use th `apply()` method.

$\Large Z \ - \ Normalization = \frac{X_i - \mu}{std} $

After that find out the below values for each group:
- minimum "Passess"
- maximum "Passess"
- minimum "Yellow Cards"
- maximum "Yellow cards"
- average "Yellow Cards"
- maximum "Attempted Line Breaks"
- minimum "Attempted Line Breaks"
- standardard deviation of "Attempted Line Breaks"
- average Possession

In [3]:
fifa = pd.read_csv('dataset/Fifa Worldcup 2022 - Sheet1.csv')

In [4]:
fifa

,Sl. No,Match No.,Team,Against,Group,Goal,Possession (%),Inside Penalty Area,Outside Penalty Area,Assists,...,Fouls Against,Offsides,Passes,Passes Completed,Crosses,Crosses Completed,Corners,Free Kicks,Penalties Scored,Pts
0,1,1,Qatar,Ecuador,A,0,40,0,0,0,...,15,3,453,387,10,5,1,19,0,0
1,2,1,Ecuador,Qatar,A,2,46,2,0,1,...,15,4,484,419,26,10,3,17,1,3
2,3,2,England,Iran,B,6,69,6,0,6,...,9,2,810,733,29,9,8,16,0,3
3,4,2,Iran,England,B,2,20,2,0,1,...,14,2,232,156,11,3,0,10,1,0
4,5,3,Senegal,Netherlands,A,0,39,0,0,0,...,13,2,391,326,22,8,6,14,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
123,124,62,Morocco,Fram,F,0,55,0,0,0,...,11,3,583,518,22,1,3,15,0,0
124,125,63,Croatia,Morocco,F,2,45,2,0,2,...,13,2,491,430,21,3,6,13,0,3
125,126,63,Morocco,Croatia,F,1,45,1,0,0,...,11,2,494,428,20,5,3,15,0,0
126,127,64,Argentina,France,C,3,46,3,0,1,...,26,4,648,544,20,4,6,22,5,3
127,128,64,France,Argentina,D,3,40,3,0,1,...,19,4,516,419,24,3,5,28,4,0

In [45]:
fifa.groupby(['Team']).groups

{'Argentina': [8, 46, 77, 98, 115, 120, 126], 'Australia': [15, 41, 72, 99], 'Belgium': [22, 50, 81], 'Brazil': [30, 60, 95, 106, 113], 'Cameroon': [25, 56, 94], 'Canada': [23, 53, 82], 'Costa Rica': [21, 49, 86], 'Croatia': [17, 52, 80, 105, 112, 121, 124], 'Denmark': [10, 45, 73], 'Ecuador': [1, 37, 66], 'England': [2, 38, 69, 102, 118], 'France': [14, 44, 75, 100, 119, 122, 127], 'Germany': [18, 55, 87], 'Ghana': [29, 59, 88], 'Iran': [3, 33, 70], 'Japan': [19, 48, 84, 104], 'Korea Republic': [27, 58, 90, 107], 'Mexico': [12, 47, 79], 'Morocco': [16, 51, 83, 108, 116, 123, 125], 'Netherlands': [5, 36, 64, 96, 114], 'Poland': [13, 42, 76, 101], 'Portugal': [28, 62, 91, 110, 117], 'Qatar': [0, 34, 65], 'Saudi Arabia': [9, 43, 78], 'Senegal': [4, 35, 67, 103], 'Serbia': [31, 57, 92], 'Spain': [20, 54, 85, 109], 'Switzerland': [24, 61, 93, 111], 'Tunisia': [11, 40, 74], 'United States': [6, 39, 71, 97], 'Uruguay': [26, 63, 89], 'Wales': [7, 32, 68]}

In [10]:
import pandas as pd

def z_normalization(group, cols_to_perform):
    group = group.copy()  # avoid SettingWithCopyWarning
    
    for col in cols_to_perform:
        std = group[col].std()
        if std != 0:
            group[col] = (group[col] - group[col].mean()) / std
        else:
            group[col] = 0  # handle division by zero
    
    return group


cols = [
    'Passes',
    'Passes Completed',
    'Attempted Line Breaks',
    'Completed Line Breaks'
]


fifa_z = fifa.copy()

for col in cols:
    mean = fifa.groupby('Team')[col].transform('mean')
    std = fifa.groupby('Team')[col].transform('std')
    
    fifa_z[col] = (fifa[col] - mean) / std


fifa_z = fifa_z.reset_index(drop=True)


result = fifa_z.groupby('Team').agg({
    'Passes': ['min', 'max'],
    'Yellow Cards': ['min', 'max', 'mean'],
    'Attempted Line Breaks': ['min', 'max', 'std'],
    'Possession (%)': 'mean'
})

result.unstack()

result

                  Passes           Yellow Cards                \
                     min       max          min max      mean
Team
Argentina      -1.510257  1.685214            0   8  2.285714
Australia      -1.114789  0.932782            0   3  1.750000
Belgium        -1.082696  0.888950            1   3  1.666667
Brazil         -0.928871  1.609122            0   3  1.200000
Cameroon       -0.875605  1.089713            1   5  2.666667
Canada         -1.120897  0.800641            2   4  2.666667
Costa Rica     -1.013178  0.986279            1   3  2.000000
Croatia        -1.441280  1.093005            0   2  1.142857
Denmark        -1.046208  0.946290            1   2  1.666667
Ecuador        -0.883020  1.085876            0   2  1.000000
England        -0.877731  1.705844            0   1  0.200000
France         -1.219077  1.571019            0   3  1.142857
Germany        -1.131449  0.765392            0   3  1.000000
Ghana          -1.045786  0.946861            2   4  2.666667
Iran           -0.820695  1.113800            2   3  2.333333
Japan          -1.001479  0.979825            0   3  1.500000
Korea Republic -1.157924  0.877868            1   2  1.500000
Mexico         -0.918398  1.065342            1   4  2.333333
Morocco        -1.384362  1.662218            0   3  1.285714
Netherlands    -1.051749  1.428668            0   4  1.800000
Poland         -0.694755  1.483035            1   3  1.750000
Portugal       -1.646177  1.035658            0   3  1.200000
Qatar          -1.147558  0.684833            0   4  2.333333
Saudi Arabia   -0.667896  1.149691            2   6  4.666667
Senegal        -1.214144  1.235077            1   3  1.750000
Serbia         -1.089807  0.875419            2   7  4.000000
Spain          -1.498758  0.554601            0   1  0.500000
Switzerland    -1.469082  0.754945            1   4  2.250000
Tunisia        -0.965692  1.031097            1   3  1.666667
United States  -1.136338  0.860862            0   4  1.250000
Uruguay        -0.931702  1.056570            1   3  2.000000
Wales          -0.971590  1.026174            1   2  1.666667

               Attempted Line Breaks                Possession (%)
                                 min       max  std           mean
Team
Argentina                  -1.027917  1.757406  1.0      49.285714
Australia                  -1.187623  0.961409  1.0      31.250000
Belgium                    -0.832050  1.109400  1.0      49.000000
Brazil                     -1.627519  1.085013  1.0      50.400000
Cameroon                   -1.124661  0.788942  1.0      38.333333
Canada                     -1.094819  0.865260  1.0      44.333333
Costa Rica                 -1.154606  0.590132  1.0      27.333333
Croatia                    -1.785063  1.187420  1.0      47.428571
Denmark                    -1.000000  1.000000  1.0      51.333333
Ecuador                    -0.979827  1.019020  1.0      42.666667
England                    -1.172641  1.354603  1.0      57.200000
France                     -1.327966  1.147789  1.0      44.857143
Germany                    -0.959538  1.036065  1.0      53.000000
Ghana                      -1.019578  0.979199  1.0      37.000000
Iran                       -1.152297  0.640642  1.0      31.666667
Japan                      -0.948495  1.377855  1.0      30.250000
Korea Republic             -1.449814  0.840338  1.0      42.250000
Mexico                     -1.154613  0.589590  1.0      46.666667
Morocco                    -1.718366  1.006855  1.0      34.285714
Netherlands                -1.222637  1.128588  1.0      44.000000
Poland                     -1.493418  0.626272  1.0      32.000000
Portugal                   -0.796941  1.655185  1.0      53.800000
Qatar                      -0.815368  1.115767  1.0      39.333333
Saudi Arabia               -1.022179  0.976238  1.0      36.666667
Senegal                    -1.077420  1.343085  1.0      38.500000
Serbia                     -0.916387  1.066614  1.0      42.666667
Spain                      -0.905726  1.193911  1.0      67.000000
Switzerland                -1.300880  1.024097  1.0      43.000000
Tunisia                    -1.119304  0.805353  1.0      38.666667
United States              -1.435367  0.767335  1.0      47.000000
Uruguay                    -0.665750  1.149932  1.0      41.000000
Wales                      -1.093756  0.867461  1.0      41.000000

## **Questions on IPL wala dataset**

ball by ball dataset - https://drive.google.com/file/d/1-kvv_9KCSAFWcrhS9WgTxSrURkRh6GNt/view?usp=share_link

### `Q-5:` Find batsman in below category-
* Highest score while chasing
* Best Strike rate while chasing and have faced 100+ balls


> Chasing mean team batting in second inning

In [2]:
ipl_del = pd.read_csv('dataset/ipl_deliveries.csv')
ipl_del

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [42]:
# 1. Highest score while chasing

ipl_del[ipl_del['innings']==2].groupby('batter')['batsman_run'].sum().sort_values(ascending=False).head(1)

batter
V Kohli    3070
Name: batsman_run, dtype: int64

In [72]:
grouped = ipl_del.groupby('innings')
grouped.get_group(2).groupby('batter')['batsman_run'].sum().sort_values(ascending=False).head(1)

batter
V Kohli    3070
Name: batsman_run, dtype: int64

In [61]:
s = ipl_del[ipl_del['innings']==2].groupby('batter')['batsman_run'].sum()
s.idxmax()

'V Kohli'

In [62]:
s.max()

np.int64(3070)

In [124]:
# 2. Best Strike rate while chasing and have faced 100+ balls

innings_2 = ipl_del[(ipl_del['innings']==2) & (ipl_del['extra_type'] != 'wides')].groupby('batter')

strike = innings_2.agg(
    runs = ('batsman_run','sum'),
    balls = ('batsman_run','count')
)

strike = strike[strike['balls']>100]

# strike.sort_values(by='balls')

strike['run_rate'] = ((strike['runs']/strike['balls']) * 100).astype(int)

strike.sort_values(by='run_rate', ascending=False, inplace=True)

strike.head(1)

            runs  balls  run_rate
batter
PJ Cummins   222    114       194

In [126]:
innings_2 = ipl_del[ipl_del['innings'] == 2]

# remove wides (important for correct balls)
innings_2 = innings_2[innings_2['extra_type'] != 'wides']

strike = innings_2.groupby('batter').agg(
    runs=('batsman_run', 'sum'),
    balls=('batsman_run', 'count')
)

# filter players with 100+ balls
strike = strike[strike['balls'] >= 100]

# calculate strike rate
strike['strike_rate'] = (strike['runs'] / strike['balls']) * 100

# sort
strike = strike.sort_values(by='strike_rate', ascending=False)

strike.head(1)

            runs  balls  strike_rate
batter
PJ Cummins   222    114   194.736842

### `Q-6` Most Successful bowler against any batsman. Find that pair of bowler and batsman.
> Most Successful in terms of dissmissal. A bowler who have dissmissed any batsman most no of times. If any two pairs have same no of dissmisal, consider runs conceded by bowler to that batsman. Those who have concede lesser runs is more successful.

In [89]:
ipl_del.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [94]:
df = ipl_del.copy()

# filter wickets (exclude run-out)
wickets = df[
    (df['isWicketDelivery'] == 1) &
    (df['kind'] != 'run out')
]

# dismissals
dismissals = wickets.groupby(['bowler', 'player_out']).size().reset_index(name='wickets')

# runs conceded
runs = df.groupby(['bowler', 'batter'])['batsman_run'].sum().reset_index(name='runs')

# merge
result = dismissals.merge(
    runs,
    left_on=['bowler', 'player_out'],
    right_on=['bowler', 'batter']
)

# clean
result = result.rename(columns={'player_out': 'batsman'})
result = result.drop(columns=['batter'])

# sort
result = result.sort_values(by=['wickets', 'runs'], ascending=[False, True])

# answer
result.head()

              bowler     batsman  wickets  runs
8047          Z Khan    MS Dhoni        7    74
7170  Sandeep Sharma     V Kohli        7    78
147         A Mishra   RG Sharma        7    87
5452        R Ashwin  RV Uthappa        7   123
6943       SP Narine   RG Sharma        7   137

### `Q-7`: Most successful batting pair in IPL. Batting pair who have scored most runs playing together.

In [127]:
ipl_del.head()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [28]:
pairs = ipl_del.copy()


pairs['pair'] = pairs.apply(
    lambda x: tuple(sorted([x['batter'],x['non-striker']])), axis=1
)


partnership = pairs.groupby('pair').agg(
    runs = ('batsman_run', 'sum'),
    extras = ('extras_run', 'sum')
)

partnership['total_runs'] = partnership['runs'] + partnership['extras']


partnership.sort_values(by='total_runs', ascending=False).head()

                           runs  extras  total_runs
pair
(AB de Villiers, V Kohli)  3040      94        3134
(CH Gayle, V Kohli)        2650     152        2802
(DA Warner, S Dhawan)      2242     115        2357
(G Gambhir, RV Uthappa)    1795     111        1906
(KL Rahul, MA Agarwal)     1664      67        1731

### `Q-8:` Make a dataframe for all batting pairs played together.
```
Batsman1 Batsman2 Runs Avg StrikeRate
```

> Just to ease this question you can count wide-balls for strike rate.

In [40]:
ipl_del.head(3)

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans

In [82]:
batting_pairs = ipl_del.copy()

batting_pairs['pairs'] = batting_pairs.apply(
    lambda x: tuple(sorted([x['batter'], x['non-striker']])), axis=1
)

partnership = batting_pairs.groupby('pairs').agg(
    Batsman1 = ('pairs', lambda x: x.iloc[0][0]),
    Batsman2 = ('pairs', lambda x: x.iloc[0][1]),
    Runs = ('batsman_run','sum'),
    Balls = ('batsman_run','count')
    ).reset_index()

partnership['Avg'] = (partnership['Runs'] / partnership['Balls']).round(2)

partnership['StrikeRate'] = ((partnership['Runs'] / partnership['Balls']) * 100).astype(int)


partnership.drop(columns = ['pairs','Balls'], inplace=True)


partnership.sort_values(by='Runs', ascending=False)

            Batsman1      Batsman2  Runs   Avg  StrikeRate
302   AB de Villiers       V Kohli  3040  1.48         147
1251        CH Gayle       V Kohli  2650  1.34         134
1508       DA Warner      S Dhawan  2242  1.30         129
1954       G Gambhir    RV Uthappa  1795  1.26         125
2803        KL Rahul    MA Agarwal  1664  1.37         137
...              ...           ...   ...   ...         ...
835     Ankit Sharma  DB Ravi Teja     0  0.00           0
828    Anirudh Singh     MD Mishra     0  0.00           0
826       Akash Deep    KD Karthik     0  0.00           0
3933        RP Singh   S Sreesanth     0  0.00           0
3932        RP Singh      RV Gomez     0  0.00           0

[4259 rows x 5 columns]

In [86]:
batting_pairs = ipl_del.copy()

# Create pairs (vectorized way)
batting_pairs['pairs'] = list(
    map(lambda x, y: tuple(sorted((x, y))),
        batting_pairs['batter'],
        batting_pairs['non-striker'])
)


# Grouping
partnership = batting_pairs.groupby('pairs').agg(
    Runs=('batsman_run', 'sum'),
    Balls=('batsman_run', 'count')
).reset_index()


# Split tuple into two columns
partnership[['Batsman1', 'Batsman2']] = pd.DataFrame(
    partnership['pairs'].tolist(), index=partnership.index
)


# Metrics
partnership['Avg'] = (partnership['Runs'] / partnership['Balls']).round(2)
partnership['StrikeRate'] = ((partnership['Runs'] / partnership['Balls']) * 100).round(2)


# Final cleanup
partnership = partnership.drop(columns=['pairs', 'Balls'])


# Sort
partnership = partnership.sort_values(by='Runs', ascending=False)


partnership

      Runs        Batsman1      Batsman2   Avg  StrikeRate
302   3040  AB de Villiers       V Kohli  1.48      147.64
1251  2650        CH Gayle       V Kohli  1.34      134.31
1508  2242       DA Warner      S Dhawan  1.30      129.97
1954  1795       G Gambhir    RV Uthappa  1.26      125.96
2803  1664        KL Rahul    MA Agarwal  1.37      137.41
...    ...             ...           ...   ...         ...
835      0    Ankit Sharma  DB Ravi Teja  0.00        0.00
828      0   Anirudh Singh     MD Mishra  0.00        0.00
826      0      Akash Deep    KD Karthik  0.00        0.00
3933     0        RP Singh   S Sreesanth  0.00        0.00
3932     0        RP Singh      RV Gomez  0.00        0.00

[4259 rows x 5 columns]